title: Ryo Chikazawa
description: JavaScript Samurai from Japan
paginate: 5
exclude: ['Gemfile*', 'Rakefile', 'README.md', 'build']

navigations:
  - title: About
    url: /about
  - title: Articles
    url: /articles
  - title: Projects
    url: /projects

assets:
  js_compressor:  uglifier
  css_compressor: sass
