title: Ryo Chikazawa
description: JavaScript Samurai
highlighter: pygments

#for feed.xml
name: RyoChikazawa.com
description: JavaScript Samurai
url: http://ryochikazawa.com

paginate: 5
exclude: ['Gemfile*', 'Rakefile', 'README.md', 'build', 'vendor']

navigations:
  - title: Top
    url: /
  - title: About
    url: /about.html
  - title: Projects
    url: /projects.html
  - title: Slides
    url: /slides.html
  - title: Japanese blog
    url: http://chikathreesix.com

socials:
  twitter:
    name: chikathreesix
    url: https://twitter.com/chikathreesix
  github:
    name: chikathreesix
    url: https://github.com/chikathreesix

ga_id: UA-53136110-1

env: development

assets:
  js_compressor:  uglifier
  css_compressor: sass
