title: Ryo Chikazawa
description: JavaScript Samurai from Japan

#for feed.xml
name: RyoChikazawa.com
description: JavaScript Samurai from Japan
url: http://ryochikazawa.com

paginate: 5
exclude: ['Gemfile*', 'Rakefile', 'README.md', 'build']

navigations:
  - title: Top
    url: /
  - title: About
    url: /about.html
  - title: Projects
    url: /projects.html
  - title: Japanese blog
    url: http://chikathreesix.com

social_links:
  twitter: https://twitter.com/chikathreesix
  github: https://github.com/chikathreesix

ga_id: UA-53136110-1

env: development

assets:
  js_compressor:  uglifier
  css_compressor: sass
